server:
  port: ${PORT:8080}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    demo:
      webflux: DEBUG
