server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # ?? ????? ??? ?????? ?? ????.

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.PostgreSQLDialect
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/template
    username: postgres
    password: postgres
    pool:
      initial-size: 10
      max-size: 20
      acquire-timeout: 30s

  jackson:
    serialization:
      fail-on-empty-beans: false

devtools:
  restart:
    enabled: true
  livereload:
    enabled: true

logging:
  level:
    org.springframework.data.r2dbc: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httpexchanges