server:
  port: ${PORT:8082}

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: ITEM_USER
    password: ITEM_PASS
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    me:
      hl:
        webfluxapi: DEBUG